const menuList = [
    {
        title:'首页',
        key:'/home',
        icon:'home'
    },
    {
        title:'系统管理',
        key:'/manager',
        icon:'setting',
        children:[
            {
                title:'模块管理',
                key:'/manager/moudle',
            },
            {
                title:'权限管理',
                key:'/manager/permission',
            },
            {
                title:'角色管理',
                key:'/manager/role',
            },
            {
                title:'NC管理',
                key:'/manager/nc',
            },
            {
                title:'用户授权',
                key:'/manager/setRole',
            },
        ]
    },
    {
        title:'企业管理',
        key:'/company',
        icon:'deployment-unit',
        children:[
            {
                title:'数据同步',
                key:'/company/syncData',
            },
            {
                title:'角色管理',
                key:'/company/role',
            },
            {
                title:'企业授权',
                key:'/company/setRole',
            },
        ]
    },
    {
        title:'数据统计',
        key:'/datasta',
        icon:'dot-chart',
        children:[
            {
                title:'基础信息统计',
                key:'/datasta/baseData',
            },
            {
                title:'单据信息统计',
                key:'/datasta/billData',
            }
        ]
    },
    {
        title:'日志管理',
        key:'/log',
        icon:'project'
    },
    
    {
        title:'内容管理',
        key:'/content',
        icon:'appstore',
        children:[
            {
                title:'首页轮播图',
                key:'/content/banner'
            }
        ]
    },
];
export default menuList;